{
  getObjects(
    bucket_slug: "srmbands-cms-production",
    read_key: "U9ZScPK1VQrXnFkthLhnRNdXjHjnkSvxBSFAMU4QtpTQWRULIl",
    input: {
    limit: 20,
    query: {
      type: "happy-to-helps"
    }
  }) {
    objects {
        id
		content
		title
        metadata
        slug
	}
}
}
        